### ISSUE TITLE
[FEATURE REQUEST] define depth of the trust net

### ISSUE THREAD

**Issue by HolgerHatGarKeineNode** [bitvora/wot-relay#19]
This relay on Github has TRUST_DEPTH features: https://github.com/CodyTseng/nostr-relay-nestjs

**Question: Is it also possible to define a depth with this relay or is this already the case?**

> WoT (Web of Trust)
> 
> If you want to enable the WoT feature, you need to set the following environment variables:
> 
>     WOT_TRUST_ANCHOR_PUBKEY: The public key of the trust anchor. Trust anchor is the root of the trust net.
>     WOT_TRUST_DEPTH: The depth of the trust net. If the trust depth is 1, the trust net will include the trust anchor and the trust anchor's following users. If the trust depth is 2, the trust net will include the trust anchor, the trust anchor's following users, and the trust anchor's following users' following users. Now the maximum trust depth is 2.
>     WOT_FETCH_FOLLOW_LIST_FROM: Comma-separated list of relay URLs to fetch follow list from (e.g., WOT_FETCH_FOLLOW_LIST_FROM=wss://nostr-relay.app,wss://relay.damus.io). This environment variable is optional. The relay will always fetch the follow list from the local database first.

Unfortunately I don't know the Go language. I am only a PHP developer. :cry:

**Comment by barrydeen** [comment]
I have tested this several times and it allows too much spam in. depth 2 is already optimal. will not be adding this feature.
