### ISSUE TITLE
build constraints exclude all Go files

### ISSUE THREAD

**Issue by markwaters** [bitvora/wot-relay#3]
When I am running the go build command it stops with this -

```
root@wotrelay:~/wot-relay# go build
github.com/PowerDNS/lmdb-go/lmdb: build constraints exclude all Go files in /root/go/pkg/mod/github.com/!power!d!n!s/lmdb-go@v1.9.2/lmdb
root@wotrelay:~/wot-relay# 
```

Any suggestions would be appreciated.

**Comment by fiatjaf** [comment]
Maybe you are running in a platform that doesn't support cgo or some other system requirement for LMDB?

**Comment by markwaters** [comment]
Thanks @fiatjaf
I am running it in a ProxMox LXC using the latest Debian.
I've previously built strfry and nostr-rs-relay under the same setup without an issue.
I'm new to Go though , so I'm probably missing something.

**Comment by fiatjaf** [comment]
No, I think I'm just wrong.

**Comment by barrydeen** [comment]
This is because missing `build-essentials` i will update dependencies. run `sudo apt install build-essentials` and it should work

**Comment by markwaters** [comment]
Fixed. Thank you.
