### ISSUE TITLE
Clarification on relay public key

### ISSUE THREAD

**Issue by Eternumkr** [bitvora/wot-relay#49]
RELAY_PUBKEY="YourPublicKey"

Would this be my own npub for the account I want to use this relay with or is it something else? 

Thank you.

**Comment by derekross** [comment]
Yes. However, it's not your ow npub though. It's the hex version of your own npub. For example: For my relay, I do not enter "npub18ams6ewn5aj2n3wt2qawzglx9mr4nzksxhvrdc4gzrecw7n5tvjqctp424". Instead, I enter "3f770d65d3a764a9c5cb503ae123e62ec7598ad035d836e2a810f3877a745b24".

**Comment by zatzby** [comment]
Derek is right, it is the hex value that goes there. You might already know how to convert but if not you can convert your npub to hex value here: https://nostrcheck.me/converter/

**Comment by barrydeen** [comment]
updated readme with some more information, thanks for reporting.
